Isolate some unit tests into separate JVMs
We do this by renaming the applicable classes to have the IT suffix
instead of Test, so that they are run by maven-failsafe-plugin each
in their own JVM. If we continue to have problems in the future,
another more aggressive option would be to make _all_ tests into ITs,
or to set the reuseForks property to false so that the surefire plugin
is forced to create a new JVM fork for each unit test class.

PROBLEM BEING SOLVED/AVOIDED:

On some Linux systems, some unit tests corrupt the state of the JVM,
such that later unit tests fail due to class loading issues. I
experimented with many combinations of unit tests, and concluded that
HelpfulExceptionTracesTest and ImagePlusTest each seem to cause this
issue. If either of them is combined with other unit tests, the other
unit tests fail. Interestingly, though, if just those two are run
together with no others, then they pass.

Note that two systems with the same version of Ubuntu and same version
of Java can exhibit two different sets of behavior. It might have to do
with the order the tests are run, but I did not check that thoroughly.

Below is an example of the worst failure observed prior to this commit,
on Ubuntu 18.04.2 LTS + openjdk 1.8.0_212. But we also observed this
same failure on an Ubuntu 16.04 system.

  [INFO] Running net.imagej.patcher.HelpfulExceptionTracesTest
  [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.28 s - in net.imagej.patcher.HelpfulExceptionTracesTest
  [INFO] Running net.imagej.patcher.HeadlessEnvironmentTest
  java.lang.RuntimeException: No _hooks field found in ij.IJ
  It appears that this class was already defined in the class loader!
  Please make sure that you initialize the LegacyService before using
  any ImageJ 1.x class. You can do that by adding this static initializer:
          static {
                  LegacyInjector.preinit();
          }
  To debug this issue, start the JVM with the option:
          -javaagent:/path/to/ij1-patcher.jar
  To enforce pre-initialization, start the JVM with the option:
          -javaagent:/path/to/ij1-patcher.jar=init
          at net.imagej.patcher.CodeHacker.javaAgentHint(CodeHacker.java:828)
          at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:433)
          at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:380)
          at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
          at net.imagej.patcher.HeadlessEnvironmentTest.<clinit>(HeadlessEnvironmentTest.java:61)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
          at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
          at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
          at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
          at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
          at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
          at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
          at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
          at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
          at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
          at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
          at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
          at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
          at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
          at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
          at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
          at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
          at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
          at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
          at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
  Caused by: java.lang.NoSuchFieldException: _hooks
          at java.lang.Class.getField(Class.java:1703)
          at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:424)
          ... 27 more
  [ERROR] Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 0.141 s <<< FAILURE! - in net.imagej.patcher.HeadlessEnvironmentTest
  [ERROR] testPluginWithDialogListener(net.imagej.patcher.HeadlessEnvironmentTest)  Time elapsed: 0.018 s  <<< ERROR!
  java.lang.ExceptionInInitializerError
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
          at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
          at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
          at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
          at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
          at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
          at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
          at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
          at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
          at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
          at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
          at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
          at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
          at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
          at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
          at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
          at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
          at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
          at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
          at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
  Caused by: java.lang.RuntimeException: Got exception (see error log)
          at net.imagej.patcher.HeadlessEnvironmentTest.<clinit>(HeadlessEnvironmentTest.java:65)
          ... 24 more
  [ERROR] booleanTest(net.imagej.patcher.HeadlessEnvironmentTest)  Time elapsed: 0.006 s  <<< ERROR!
  java.lang.NoClassDefFoundError: Could not initialize class net.imagej.patcher.HeadlessEnvironmentTest
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
          at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
          at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
          at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
          at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
          at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
          at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
          at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
          at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
          at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
          at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
          at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
          at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
          at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
          at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
          at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
          at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
          at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
          at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
          at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)