Silently eat error if old Apple classes not found
On all modern (Java 9+) JVMs, the com.apple.eawt package no longer
exists, having been replaced by a platform-independent approach:

  https://openjdk.java.net/jeps/272

Still, ImageJ1 tries to run its MacAdapter, which depends on
com.apple.eawt classes, which cannot be loaded, thus triggering
NoClassDefFoundError. ImageJ1 normally silently eats this error,
but the ij1-patcher injects code to complain more loudly when classes
are not found. But let's make an exception (ha ha) in this case.